version: "3.6"
services:
  asoprox-core-frontend:
    container_name: asoprox-core-frontend-con
    build: ./frontend
    ports: 
      - 5000:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
  asoprox-core-backend:
    build: ./backend
    depends_on:
      - db
    environment:
      PORT: 5001
      NODE_ENV: dev
    ports: 
      - 5001:5001
    container_name: asoprox-core-backend-con
    volumes:
      - ./backend/src:/app/src
  db:
    image: mysql
    restart: always
    container_name: asoprox-core-db-con
    environment:
      MYSQL_DATABASE: 'asoprox-core-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: